name: Deploy MkDocs to Documentation Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings

      - name: Build the MkDocs site
        run: mkdocs build

      - name: Clone the Documentation Repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git clone --branch gh-pages https://${{ secrets.ACCESS_TOKEN }}@github.com/acceleratescience/workshops.git workshops

      - name: Deploy to Documentation Repo
        run: |
          rsync -av --delete ./site/ workshops/packaging-publishing/
          cd workshops
          git add .
          git commit -m "Deploy packaging-publishing to /packaging-publishing"
          git push



